apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: node-app
      tier: mynode
  template:
    metadata:
      labels:
        app: node-app
        tier: mynode
    spec:
      containers:
      - name: node-app
        image: lakshmimohanapriyam232/my_image_lakshmi:latest
        ports:
        - containerPort: 3000